version: '2'

services:
    dremio:
        image: dremio/dremio-oss
        volumes:
        - ~/volumes/data-portal/dremio/data:/opt/dremio/data
        ports:
        - "9047:9047"
        - "31010:31010"
        - "45678:45678"
